language: node_js
node_js:
  - 12.18.4
cache: npm

install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
  branch: gh-pages
# HOOKS
# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:
